version: 1

defaults:
  schema_mode: raw_string
  chunk_size: 50000

tables:
  - id: ZTIF9001
    enabled: true
    query_file: ../queries/ZTIF9001.sql

    bq_project: ga4-bigquery
    bq_dataset: HANABQ
    bq_table: ZTIF9001

    window_column: INTEG_RDATE
    window_format: yyyymmdd

    runs:
      - name: daily
        schedule: "0 5 * * *"
        load_strategy: window_replace
        allow_empty: true
        window:
          type: rolling_days
          days: 2

      - name: monthly
        schedule: "30 5 8 * *"
        load_strategy: window_replace
        allow_empty: true
        window:
          type: previous_month

      - name: backfill_once
        schedule: null
        load_strategy: replace
        allow_empty: false
